name: NewYearCountdown
version: ${project.version}
main: com.example.nyc.NewYearPlugin
api-version: 1.21
authors: [YourName]
description: 适配 Minecraft 1.21.11 的跨年烟花倒计时插件
commands:
  ny:
    description: 跨年倒计时主指令
    usage: /ny <start|stop>
    permission: ny.admin
    permission-message: 你没有权限执行此操作
