name: NewYearCountdown
version: 1.0.0
main: com.example.nyc.NewYearCountdown
api-version: 1.21
description: 1.21.1 跨年倒计时插件
commands:
  nyc:
    description: 控制跨年倒计时
    usage: /nyc <start|stop>
    permission: nyc.admin
    permission-message: §c你需要管理员权限才能使用此指令！
permissions:
  nyc.admin:
    description: 允许使用倒计时控制指令
    default: op
